### ISSUE TITLE
Unresolved externals while executing --compile-cxx on sample

### ISSUE THREAD

**Issue by compile0219** [nirai-compiler/src#9]
Fresh (for this even) Windows 7 install. Tried running 32-bit mode on a 64-bit Windows 7 install, then due to it not liking that if I didn't run it in that mode (but working, but doing the same thing it does now), I just did a fresh 32-bit install instead to simplify this process as much as possible without any extra commands. Obviously I don't get the error relating to the 64-bit system as it's now on a 32-bit system, however I am getting another error which they both shared.

I did copy this over from the other drive (which was also just as fresh, just 64-bit) however all of the software installs are also fresh. It did this on both versions of Windows.

So basically, everything but this was done on a 64-bit system, and now I have moved it all (with freshly reinstalled third party programs, like the SDK) to a 32-bit system. If I started over and compiled Panda3D on this version of Windows 7 would it make a difference? Didn't seem to matter during the compilation of that at all, but would it have an effect now?

Takes about 50 seconds of spewing out these to get to the bottom. I've compiled Panda3D (and ran postbuild), pythonembed, AES, did --make-nri, all successfully. Basically the last step of everything and it finally fails.

Screenshot: http://i.imgur.com/JNWFlb4.png

Using "python -OO make.py --compile-cxx" in the Windows 7 x86 Debug Build Environment command window.

**Comment by loblao** [comment]
It looks like there's something wrong with pythonembed. Could you zip and upload it?

**Comment by compile0219** [comment]
Alright, thanks. Here you go.

[pythonembed.zip](https://github.com/nirai-compiler/src/files/264047/pythonembed.zip)

**Comment by compile0219** [comment]
Just rebuilt it (might have done something wrong in the command line with cmake previously), looks like it doubled the file size x2. Going to give it a whirl.

**Comment by compile0219** [comment]
Now down to 2, hooray: http://i.imgur.com/FYLettw.png

Want the file again?

**Comment by compile0219** [comment]
Any ideas?

**Comment by loblao** [comment]
Please send your file.

**Comment by compile0219** [comment]
Sorry for the long delay. Here is the file.

[pythonembed.zip](https://github.com/nirai-compiler/src/files/303850/pythonembed.zip)

**Comment by compile0219** [comment]
Hey loblao, any updates on this? Thanks so much! @loblao

**Comment by ghost** [comment]
I could supply you with my pythonembed, it has nothing wrong with it from what I can tell.

**Comment by compile0219** [comment]
That would be great. Thanks!

**Comment by ghost** [comment]
[pythonembed.zip](https://github.com/nirai-compiler/src/files/400634/pythonembed.zip)
Here you go!
If it doesn't work, I won't be able to help, unfortunately. The reason Nirai doesn't offer precompiled binaries is due to compatibility issues.
This pythonembed was compiled on a 64-bit machine running Windows 10.

**Comment by padlocks** [comment]
Any help would be appreciated. I get these errors when I try to compile some source. 
I have looked through other issues and couldn't find any use for them, the pythonembeded.lib you sent fixes 2 of the unresolved external symbols, but not all 7. I built mine as a win32 application, if any more information is needed please let me know.

"E:\Panda3D-1.10.0\python\ppython.exe" -OO make.py -cnm

Compiling CXX codes...
aes.cxx
main.cxx
stride.cxx
Linking...
   Creating library built/infinity.lib and object built/infinity.exp
main.obj : error LNK2001: unresolved external symbol _initdirect
main.obj : error LNK2001: unresolved external symbol "void __cdecl init_libmotiontrail(void)" (?init_libmotiontrail@@YAXXZ)
main.obj : error LNK2001: unresolved external symbol _initcore
stride.obj : error LNK2001: unresolved external symbol _initlibpandadna
stride.obj : error LNK2001: unresolved external symbol "void __cdecl init_libpandadna(void)" (?init_libpandadna@@YAXXZ)
built/infinity.exe : fatal error LNK1120: 5 unresolved externals

**Comment by lolman8776** [comment]
@emiily You're going to need libpandadna. Cmake that, then in that project directory (after building it with VS2010 (Set build mode to release!)), copy the libpandadna.dir directory to your build folder. On line 111 of make.py (If you're using Stride, which you are), add this line: `compiler._built |= set(glob.glob('libpandadna.dir/Release/*.obj'))`. For the other errors, make sure your local version of Nirai (build/nirai/src) is up-to-date, as the other errors have been fixed.

**Comment by ghost** [comment]
@emiily Download the Nirai panda source again, and edit compile.bat and remove `--no-pandatool` and `--static`, and for faster build times, go ahead and add `--no-eigen` (optional). Now, you're going to need libpandadna. Extract the source into desktop, and edit CMakeLists.txt and change the panda3d directory to where your freshly built non static Panda3d is (the built folder in that new p3d), and cmake it. Then in that project directory (after building it with VS2010 (Set build mode to release!)), copy the libpandadna.dir directory to your build folder. On line 111 of make.py (If you're using Stride, which you are), add this line: `compiler._built |= set(glob.glob('libpandadna.dir/Release/*.obj'))`. For the other errors, make sure your local version of Nirai (build/nirai/src) is up-to-date, as the other errors have been fixed.

**Comment by padlocks** [comment]
@lolman8776 I attached my BuildLog in a zip file. I'm trying to build libpandadna, I get 4 errors.

Incase it's something else, I get 25 unresolved externals. I put a file showing the logs in the zip

(For some reason I couldn't attach my zip file, so go [here](https://i.emiily.pw/files/logs.zip) to download it.)

**Comment by ghost** [comment]
You need to build your actual stride.cxx executable on the NORMAL panda3d (the one that you didn't modify the compile.bat for), and build libpandadna against the one you DID modify compile.bat for. I can give you my .obj files for Libpandadna, too. But, if it doesn't work, I can't help you and it must be because of compatibility issues. I have attached the obj files. Extract the libpandadna.dir folder into your build directory (The same directory as your make.py).
[libpandadna.zip](https://github.com/nirai-compiler/src/files/410092/libpandadna.zip)

**Comment by padlocks** [comment]
I still get the error, ultimately. Not sure what you mean by building stride.cxx, however. I was also able to build libpandadna myself, can't remember what I did there.

**Comment by ghost** [comment]
When you run make.py with -c or -compile-cxx, you're building stride.cxx. That's the code that sets up your executable. You built libpandadna on the panda3d that you edited the compile.bat and removed `--static` and `--no-pandatool` for, and you built the `make.py --compile-cxx` executable using the panda3d that _didn't_ have the modified compile.bat, right? If so, you shouldn't have any trouble.
EDIT: On the panda3d you edited the compile.bat for, you didn't run postbuild, did you? If so, that was the problem with libpandadna.

**Comment by padlocks** [comment]
I didn't. But, I'm still having issues. ):
(Also I now see the cxx thing >.>)

```
Compiling CXX codes...
aes.cxx
infinity.cxx
main.cxx
Linking...
   Creating library built/infinity.lib and object built/infinity.exp
infinity.obj : error LNK2001: unresolved external symbol "private: static class TypeHandle TypeHandle::_none" (?_none@TypeHandle@@0V1@A)
infinity.obj : error LNK2001: unresolved external symbol "class TypeHandle uchar_type_handle" (?uchar_type_handle@@3VTypeHandle@@A)
infinity.obj : error LNK2001: unresolved external symbol "class MemoryHook * memory_hook" (?memory_hook@@3PAVMemoryHook@@A)
infinity.obj : error LNK2001: unresolved external symbol "private: static class MemoryUsage * MemoryUsage::_global_ptr" (?_global_ptr@MemoryUsage@@0PAV1@A)
infinity.obj : error LNK2001: unresolved external symbol "private: static class TypeHandle ReferenceCount::_type_handle" (?_type_handle@ReferenceCount@@0VTypeHandle@@A)
infinity.obj : error LNK2001: unresolved external symbol "private: static class TypeHandle NodeReferenceCount::_type_handle" (?_type_handle@NodeReferenceCount@@0VTypeHandle@@A)
infinity.obj : error LNK2001: unresolved external symbol "private: static class TypeHandle TypedObject::_type_handle" (?_type_handle@TypedObject@@0VTypeHandle@@A)
infinity.obj : error LNK2001: unresolved external symbol "private: static class TypeHandle Datagram::_type_handle" (?_type_handle@Datagram@@0VTypeHandle@@A)
infinity.obj : error LNK2001: unresolved external symbol _initlibpandadna
infinity.obj : error LNK2001: unresolved external symbol "void __cdecl init_libpandadna(void)" (?init_libpandadna@@YAXXZ)
built/infinity.exe : fatal error LNK1120: 10 unresolved externals
```

**Comment by ghost** [comment]
Can you attach infinity.cxx so that I can see if I can fix it (Mine needed modification to work)? Also, you don't need to hide that you're using Stride code, it says in their repository's readme that the TTS team welcomes you to build upon the code :)

**Comment by padlocks** [comment]
Not hiding, just trying to create a server for some close friends without getting my custom source leaked. Anyways, here you go: [infinity.cxx](https://i.emiily.pw/files/infinity.zip)

**Comment by ghost** [comment]
Alright then, that's fine too. I'll get to work on fixing it and I'll see what I can do.

**Comment by ghost** [comment]
I believe your issue is actually caused by a broken libpandadna build. Try mine and see your results.
P.S: CHANGE YOUR ENCRYPTION KEY! I've commented "CHANGEME" on what you need to change. Make sure you change the
letters to something random. Otherwise, anyone can find the TTS key and dump your source.
Make sure to change it in make.py, too. Just search for the old key (The one I commented CHANGEME on.). If you 
don't, the game will not run, because it cannot decrypt ToonData.bin due to an incorrect key.
P.P.S: You need to change the header size to 10, because TTINFINITY is 10 characters long. I have done that for you in the edited version attached.
[Here you are!](https://github.com/nirai-compiler/src/files/416368/infinity.zip)

**Comment by padlocks** [comment]
Thank you for that. I can't even compile p3d anymore for some reason. I either get: 
`LNK1112: module machine type 'x64' conflicts with target machine type 'X86'"`
or unresolved externals.
If possible, could you attach your built panda3d?

**Comment by LanceBladestorme** [comment]
I'm face a similar issue. Anyone able to help?
`Setting environment for using Microsoft Visual Studio 2010 x86 tools.

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC>cd C:\Pie Legion Server\ToontownStride-master\build

C:\Pie Legion Server\ToontownStride-master\build>python -OO make.py --compile-cxx
Compiling CXX codes...
aes.cxx
main.cxx
stride.cxx
Linking...
   Creating library built/stride.lib and object built/stride.exp
main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static void __cdecl AudioManager::register_AudioManager_creator(class AudioManager * (__cdecl*)(void))" (__imp_?register_AudioManager_creator@AudioManager@@SAXP6APAV1@XZ@Z)
main.obj : error LNK2001: unresolved external symbol "class AudioManager * __cdecl Create_OpenALAudioManager(void)" (?Create_OpenALAudioManager@@YAPAVAudioManager@@XZ)
main.obj : error LNK2001: unresolved external symbol __imp__init_libOpenALAudio
main.obj : error LNK2001: unresolved external symbol _initphysics
main.obj : error LNK2001: unresolved external symbol _initode
main.obj : error LNK2001: unresolved external symbol _initfx
main.obj : error LNK2001: unresolved external symbol _initegg
main.obj : error LNK2001: unresolved external symbol _init_direct
main.obj : error LNK2001: unresolved external symbol "void __cdecl init_libpnmimagetypes(void)" (?init_libpnmimagetypes@@YAXXZ)
main.obj : error LNK2001: unresolved external symbol "void __cdecl init_libmovies(void)" (?init_libmovies@@YAXXZ)
main.obj : error LNK2001: unresolved external symbol "void __cdecl init_libwgldisplay(void)" (?init_libwgldisplay@@YAXXZ)
main.obj : error LNK2001: unresolved external symbol _init_core
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall DatagramIterator::~DatagramIterator(void)" (__imp_??1DatagramIterator@@QAE@XZ)
stride.obj : error LNK2001: unresolved external symbol _initlibpandadna
stride.obj : error LNK2001: unresolved external symbol "void __cdecl init_libpandadna(void)" (?init_libpandadna@@YAXXZ)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall Datagram::~Datagram(void)" (__imp_??1Datagram@@UAE@XZ)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall PointerToArray<unsigned char>::size(void)const " (__imp_?size@?$PointerToArray@E@@QBEIXZ)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall DatagramIterator::extract_bytes(unsigned int)" (__imp_?extract_bytes@DatagramIterator@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: int __thiscall DatagramIterator::get_int32(void)" (__imp_?get_int32@DatagramIterator@@QAEHXZ)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall DatagramIterator::get_string(void)" (__imp_?get_string@DatagramIterator@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall DatagramIterator::get_uint32(void)" (__imp_?get_uint32@DatagramIterator@@QAEIXZ)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall DatagramIterator::DatagramIterator(class Datagram const &,unsigned int)" (__imp_??0DatagramIterator@@QAE@ABVDatagram@@I@Z)
stride.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall Datagram::Datagram(void const *,unsigned int)" (__imp_??0Datagram@@QAE@PBXI@Z)
built/stride.exe : fatal error LNK1120: 23 unresolved externals
The following command returned non-zero value (1120): link /LTCG /LTCG:STATUS /nologo /out:built/stride.exe "built/aes.obj" "built/main.obj" "built/stride...`

**Comment by ghost** [comment]
Sorry for the (extremely) late reply, but you should submit your current problem as a new issue.
